kind: pipeline
name: default

clone:
  depth: 5

steps:
- name: exec antenna
  image: matsubara0507/antenna
  environment:
    GIT_NAME: BOT
    SSH_KEY:
      from_secret: deploy_key
  commands:
  - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
  - git clone -b gh-pages git@github.com:haskell-jp/antenna.git temp
  - cp sites.yaml temp/sites.yaml
  - cp -r image/* temp/image
  - cd temp
  - antenna sites.yaml
  - git config --global user.name "$GIT_NAME"
  - git status
  - git add -A
  - git diff --quiet && git diff --staged --quiet || git commit -am "[skip ci] Update planet haskell. See https://haskell.jp/antenna/ for new entries!"
  - git push origin gh-pages
  when:
    branch: drone
