kind: pipeline
name: default

clone:
  depth: 5

steps:
- name: exec antenna
  image: matsubara0507/antenna
  environment:
    GH_TOKEN:
      from_secret: github_api_token
    GIT_NAME: BOT
  commands:
  - git clone -b gh-pages "https://${GH_TOKEN}@github.com/haskell-jp/antenna.git" temp
  - cp sites.yaml temp/sites.yaml
  - cp -r image/* temp/image
  - cd temp
  - antenna sites.yaml
  - git config user.name "${GIT_NAME}"
  - git status
  - git add -A
  - git diff --quiet && git diff --staged --quiet || git commit -am "[skip ci] Update planet haskell. See https://haskell.jp/antenna/ for new entries!"
  - git push origin gh-pages
  when:
    branch: drone
