kind: pipeline
name: default

clone:
  depth: 5

steps:
- name: clone gh-pages
  image: matsubara0507/git-with-ssh
  setteings:
    ssh-private-key:
      from_secret: deploy_key
    hosts:
    - github.com
    commands:
    - git clone -b gh-pages git@github.com:haskell-jp/antenna.git temp
  when:
    branch:
    - git-with-ssh-plugin
    - master
    event:
      exclude:
      - pull_request

- name: exec antenna
  image: haskelljp/antenna
  commands:
  - mkdir -p temp
  - cp sites.yaml temp/sites.yaml
  - cp -r image/* temp/image
  - cd temp
  - antenna sites.yaml

- name: push gh-pages
  image: docker:git
  setteings:
    ssh-private-key:
      from_secret: deploy_key
    hosts:
    - github.com
    commands:
    - cd temp && git config user.name  BOT
    - cd temp && git config user.email bot@example.com
    - cd temp && git status
    - cd temp && git add -A
    - cd temp && git diff --quiet && git diff --staged --quiet || git commit -am "[skip ci] Update planet haskell. See https://haskell.jp/antenna/ for new entries!"
    - cd temp && git push origin gh-pages
  when:
    branch:
    - git-with-ssh-plugin
    - master
    event:
      exclude:
      - pull_request
