sudo: required
services:
  - docker
language: generic
cache:
  timeout: 360
  directories:
  - "$HOME/.stack/"
  - "$HOME/.local/bin/"
  - ".stack-work/"
install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
jobs:
  include:
    - stage: build dependencies
      script: stack --no-terminal --install-ghc test --bench --only-dependencies
    - stage: build antenna
      script: stack --no-terminal build --bench --no-run-benchmarks --no-haddock-deps --pedantic
