name:                antenna
version:             0.2.1.0
github:              "haskell-jp/antenna"
license:             MIT
author:              "MATSUBARA Nobutada"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/haskell-jp/antenna#readme>

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

executables:
  antenna:
    main: Main.hs
    source-dirs: app
    dependencies:
    - blaze-html
    - extensible >= 0.6
    - githash
    - mix
    - scrapbook-core >= 0.4
    - yaml
