resolver: lts-17.0
packages:
- .
extra-deps:
- drinkery-0.4
- extensible-0.8.1
- membership-0
- incremental-0.3.1
- github: matsubara0507/scrapbook
  commit: 1839569c8ca1bb22c1f415b33dbee733e8f7e27c
  subdirs:
  - lib/scrapbook-core
- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
  - mix-plugin-shell

docker:
  repo: matsubara0507/stack-build
  enable: false
