resolver: lts-14.20
packages:
- .
extra-deps:
- drinkery-0.4
- extensible-0.7
- membership-0
- git: https://github.com/matsubara0507/scrapbook.git
  commit: 9ed6874c12ce53b99569a9952253e89859148cf5
  subdirs:
  - lib/scrapbook-core
- github: matsubara0507/mix.hs
  commit: 4978a33dec736799b30c14e215f7fa0f29fa2884
  subdirs:
  - mix

docker:
  repo: matsubara0507/stack-build
  enable: false
