resolver: lts-11.6
packages:
- .
extra-deps:
- data-default-instances-text-0.0.1
- drinkery-0.3
- git: https://github.com/matsubara0507/scrapbook.git
  commit: 2286af3abc98fa71801cea386f4cc38d882ce36d
- git: https://github.com/matsubara0507/extensible-instances.git
  commit: a5b543cede63890c84d3f62f9c26349ae9f2e4fc
- rio-0.1.1.0
