resolver: lts-14.4
packages:
- .
extra-deps:
- drinkery-0.4
- extensible-0.6.1
- membership-0
- git: https://github.com/matsubara0507/scrapbook.git
  commit: 9ed6874c12ce53b99569a9952253e89859148cf5
  subdirs:
  - lib/scrapbook-core

docker:
  repo: fpco/stack-build
  enable: false
