resolver: lts-10.8
packages:
- .
extra-deps:
- drinkery-0.1
- git: https://github.com/matsubara0507/scrapbook.git
  commit: ebc9f7067558c890a1c225c9b8bbbe2bd2b109ca
- git: https://github.com/matsubara0507/extensible-instances.git
  commit: 8dabe7a3dd9cf162e2d81e4ca16dbe73b98a3809
