resolver: lts-11.6
packages:
- .
extra-deps:
- data-default-instances-text-0.0.1
- drinkery-0.3
- git: https://github.com/matsubara0507/scrapbook.git
  commit: 05cb7ac27c0e8364415ee1a76767c0b8f1286569
- git: https://github.com/matsubara0507/extensible-instances.git
  commit: a5b543cede63890c84d3f62f9c26349ae9f2e4fc
- rio-0.1.1.0
