- name: Haskell情報
  show-default: Yes
  sources:
    - name: Qiita
      label: qiita
      url: http://qiita.com/tags/Haskell/feed
    - name: スタック・オーバーフロー
      label: stack-overflow
      url: http://ja.stackoverflow.com/feeds/tag?tagnames=haskell&sort=newest
- name: ブログ
  show-default: No
  sources:
    - name: flip map
      label: lotz84.github.io
      url: https://lotz84.github.io/feed.xml
- name: 英語
  show-default: No
  sources:
    - name: "Haskell :: Reddit"
      label: reddit-haskell
      url: https://www.reddit.com/r/haskell/.rss
